import React from 'react';
import './styling.css';
import './script.js'

export default function Footer() {
  return (
    <div className = "">
<div class="container">
    <div class="season"></div>
    <div class="sun"></div>
    <div class="rainbow">
      <div class="rainbow-colour"></div>
      <div class="rainbow-colour"></div>
      <div class="rainbow-colour"></div>
      <div class="rainbow-colour"></div>
      <div class="rainbow-colour"></div>
      <div class="rainbow-colour"></div>
      <div class="rainbow-colour"></div>
    </div>
    <div class="cloud-group">
      <div class="cloud">
        <div class="weather-container">
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
        </div>
      </div>
      <div class="cloud">
        <div class="weather-container">
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
        </div>
      </div>
      <div class="cloud">
        <div class="weather-container">
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
        </div>
      </div>
      <div class="cloud">
        <div class="weather-container">
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
        </div>
      </div>
      <div class="cloud">
        <div class="weather-container">
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
        </div>
      </div>
      <div class="cloud">
        <div class="weather-container">
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
        </div>
      </div>
      <div class="cloud">
        <div class="weather-container">
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
        </div>
      </div>
      <div class="cloud">
        <div class="weather-container">
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="snow"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
          <div class="rain"></div>
        </div>
      </div>
    </div>
    <div class="base">
      <div class="bush-group">
        <div class="bush"></div>
        <div class="bush"></div>
        <div class="bush"></div>
        <div class="bush"></div>
        <div class="bush"></div>
        <div class="bush"></div>
        <div class="bush"></div>
        <div class="bush"></div>
        <div class="bush"></div>
      </div>
      <div class="rabbit animated">
        <div class="head">
          <div class="ear"></div>
          <div class="ear"></div>
        </div>
      </div>
      <div class="tree-group">
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top"></div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top"></div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top"></div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="branch"></div>
          <div class="branch"></div>
          <div class="branch"></div>
          <div class="branch"></div>
          <div class="branch"></div>
          <div class="branch"></div>
          <div class="branch"></div>
          <div class="branch"></div>
          <div class="branch"></div>
          <div class="branch"></div>
          <div class="branch"></div>
          <div class="branch"></div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top"></div>
          <div class="tree-top"></div>
          <div class="branch-two">
            <div class="tree-top"></div>
          </div>
          <div class="branch-two">
            <div class="tree-top"></div>
          </div>
          <div class="branch-two">
            <div class="tree-top"></div>
          </div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top"></div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top"></div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top">
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
          </div>
          <div class="tree-top"></div>
          <div class="tree-top"></div>
          <div class="flower">
            <div class="flower-in"></div>
            <div class="petal"></div>
            <div class="petal"></div>
            <div class="petal"></div>
          </div>
          <div class="flower">
            <div class="flower-in"></div>
            <div class="petal"></div>
            <div class="petal"></div>
            <div class="petal"></div>
          </div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top"> </div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="branch">
            <div class="branch-in"></div>
            <div class="pine-cone-row">
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
            </div>
          </div>
          <div class="branch">
            <div class="branch-in"></div>
            <div class="pine-cone-row">
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
            </div>
          </div>
          <div class="branch">
            <div class="branch-in"></div>
            <div class="pine-cone-row">
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
            </div>
          </div>
          <div class="branch">
            <div class="branch-in"></div>
            <div class="pine-cone-row">
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
            </div>
          </div>
          <div class="branch">
            <div class="branch-in"></div>
            <div class="pine-cone-row">
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
            </div>
          </div>
          <div class="branch">
            <div class="branch-in"></div>
            <div class="pine-cone-row">
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
            </div>
          </div>
          <div class="branch">
            <div class="branch-in"></div>
            <div class="pine-cone-row">
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
            </div>
          </div>
          <div class="branch">
            <div class="branch-in"></div>
            <div class="pine-cone-row">
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
            </div>
          </div>
          <div class="branch">
            <div class="branch-in"></div>
            <div class="pine-cone-row">
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
            </div>
          </div>
          <div class="branch">
            <div class="branch-in"></div>
            <div class="pine-cone-row">
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
              <div class="pine-cone"></div>
            </div>
          </div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top"></div>
          <div class="tree-top"></div>
          <div class="tree-top"></div>
        </div>
        <div class="tree">
          <div class="trunk"> </div>
          <div class="tree-top">
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
          </div>
          <div class="tree-top"></div>
          <div class="tree-top"></div>
          <div class="flower">
            <div class="flower-in"></div>
            <div class="petal"></div>
            <div class="petal"></div>
            <div class="petal"></div>
          </div>
          <div class="flower">
            <div class="flower-in"></div>
            <div class="petal"></div>
            <div class="petal"></div>
            <div class="petal"></div>
          </div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top"> </div>
          <div class="tree-top"></div>
          <div class="tree-top"></div>
          <div class="branch-two">
            <div class="tree-top"></div>
          </div>
          <div class="branch-two">
            <div class="tree-top"></div>
          </div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top">
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
          </div>
          <div class="tree-top">
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
          </div>
          <div class="tree-top">
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
            <div class="cone"> </div>
          </div>
        </div>
        <div class="tree">
          <div class="trunk"></div>
          <div class="tree-top">
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
            <div class="cone">      </div>
          </div>
          <div class="tree-top">
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
            <div class="cone">       </div>
          </div>
          <div class="tree-top">
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
            <div class="cone"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  )
}